version: '3.8'

services:
  quentin:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./index.html:/access_point/index.html
    networks:
      - my_network

  client:
    image: alpine:latest
    depends_on:
      - quentin
    command: sh -c "apk update && apk add --no-cache curl && tail -f /dev/null"
    volumes:
      - ./ssl:/ssl
    networks:
      - my_network

  client_wo_cert:
    image: alpine:latest
    command: sh -c "apk update && apk add --no-cache curl && tail -f /dev/null"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
