apiVersion: v1
kind: Pod
metadata:
  name: secret-mount-pod
spec:
  containers:
    - name: my-container
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
